name: Testcode

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-20.04
    steps:
      - name: test
        run: echo "Hello"
        shell: bash
